name: "Build HAOS Installer ISO"

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '请输入haos下载地址(扩展名 .img.gz/.img.xz/.img.zip)'
        required: true
        default: 'https://github.com/home-assistant/operating-system/releases/download/15.0/haos_generic-x86-64-15.0.img.xz'

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: Set executable permissions
        run: |
          chmod +x "${{ github.workspace }}/haos.sh"
          chmod +x "${{ github.workspace }}/supportFiles/haos/build.sh"

      - name: Validate Download URL
        run: |
          USER_INPUT_URL="${{ github.event.inputs.download_url }}"
          
          if [[ ! "$USER_INPUT_URL" =~ ^https?://.+\.[gG][zZ]$|^https?://.+\.[xX][zZ]$|^https?://.+\.[zZ][iI][pP]$ ]]; then
            echo "❌ 错误：地址需以 http(s) 开头且扩展名为 .gz/.xz/.zip"
            echo "当前输入：$USER_INPUT_URL"
            exit 1
          fi

      - name: "Build Image"
        run: |
          download_url="${{ github.event.inputs.download_url }}"
          ./haos.sh "$download_url"

      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "HAOS-Installer-x86_64-ISO"
          body_path: "${{ github.workspace }}/supportFiles/haos/info.md"
          files: |
            output/haos-installer-x86_64.iso
          token: "${{ secrets.GITHUB_TOKEN }}"