name: "Build iStoreOS Installer ISO"

on:
 workflow_dispatch:

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:

      - name: "Checking out git repository"
        uses: actions/checkout@v2
      
      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/istoreos.sh
          chmod +x ${{ github.workspace }}/supportFiles/istoreos/build.sh

      - name: "Build iStoreOS Installer ISO"
        run: |
          ./istoreos.sh
      
      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "iStoreOS-Installer-x86_64-ISO"
          body_path: ${{ github.workspace }}/supportFiles/istoreos/info.md
          files: |
            output/istoreos-installer-x86_64.iso
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
